'use server';
/**
 * @fileOverview Infrastructure Engagement Analysis Flow.
 * Synthesizes core adoption and economic metrics for executive decision intelligence.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AnalyzeEngagementMetricsInputSchema = z.object({
  retailerId: z.string().optional(),
}).optional();

const EngagementSchema = z.object({
    totalScans: z.number().describe('All platform entry points.'),
    uniqueScans: z.number().describe('Total individual behavioural nodes.'),
    identifiedShoppers: z.number().describe('Smart Profile conversion volume.'),
    profileConversionRate: z.number().describe('Efficiency of the Identity Layer.'),
    engagementDuration: z.number().describe('Depth of decision-window interaction.'),
    scanRate: z.number().describe('Infrastructure velocity.'),
    authMethodBreakdown: z.object({
        google: z.number(),
        apple: z.number(),
        phone: z.number(),
        email: z.number(),
    }),
});

const ConversionSchema = z.object({
      avgBasketSizeAoe: z.number().describe('Transaction value with Intelligence guidance.'),
      avgBasketSizeNonAoe: z.number().describe('Transaction value baseline.'),
      basketSizeIncreaseRand: z.number().describe('Basket size increase in Rand value.'),
      basketSizeIncreasePercent: z.number().describe('Basket size increase in percentage.'),
      revenueInfluenced: z.number().describe('Total revenue from shoppers who engaged with the platform.'),
      incrementalRevenue: z.number().describe('Net new revenue generated by the Intelligence Layer.'),
      salesUpliftPercentage: z.number().describe('Percentage increase in total sales attributable to AOE.'),
      conversionRate: z.number().describe('Standard conversion rate.'),
      scanToPurchaseConversion: z.number().describe('Percentage of scans resulting in a purchase.'),
      assistedSales: z.number().describe('Total volume of sales directly guided by AI Assistant.'),
      offerRedemptionRate: z.number().describe('Network monetisation velocity.'),
      totalRedeemedValue: z.number(),
      aoeTransactions: z.number().describe('Total volume influenced by decision intelligence.'),
});

const AnalyzeEngagementMetricsOutputSchema = z.object({
  engagement: EngagementSchema,
  conversion: ConversionSchema,
  overallPerformance: z.string().describe('High-level executive summary of ecosystem health.'),
  conclusions: z.string().describe('Strategic findings from behavioural patterns.'),
  recommendations: z.string().describe('ROI-driven tactical action plan.'),
});
export type AnalyzeEngagementMetricsOutput = z.infer<typeof AnalyzeEngagementMetricsOutputSchema>;

export async function analyzeEngagementMetrics(input?: z.infer<typeof AnalyzeEngagementMetricsInputSchema>): Promise<AnalyzeEngagementMetricsOutput> {
  return analyzeEngagementMetricsFlow(input);
}

const analyzeEngagementMetricsFlow = ai.defineFlow(
  {
    name: 'analyzeEngagementMetricsFlow',
    inputSchema: AnalyzeEngagementMetricsInputSchema,
    outputSchema: AnalyzeEngagementMetricsOutputSchema,
  },
  async () => {
    // Infrastructure Simulation Data
    const uniqueScans = 3210;
    const identifiedShoppers = 1184;

    const engagement = {
        totalScans: 4829,
        uniqueScans,
        identifiedShoppers,
        profileConversionRate: (identifiedShoppers / uniqueScans) * 100,
        engagementDuration: 32,
        scanRate: 5.4,
        authMethodBreakdown: {
            phone: 45,
            google: 32,
            apple: 15,
            email: 8,
        }
    };

    const avgBasketSizeNonAoe = 185.50;
    const basketUpliftPercentage = 12.5;
    const avgBasketSizeAoe = avgBasketSizeNonAoe * (1 + basketUpliftPercentage / 100);
    const basketSizeIncreaseRand = avgBasketSizeAoe - avgBasketSizeNonAoe;

    const aoeTransactions = Math.floor(uniqueScans * 0.25); // 25% purchase rate after engagement
    const revenueInfluenced = aoeTransactions * avgBasketSizeAoe;
    const incrementalRevenue = aoeTransactions * basketSizeIncreaseRand;

    const conversion = {
        avgBasketSizeAoe,
        avgBasketSizeNonAoe,
        basketSizeIncreaseRand,
        basketSizeIncreasePercent: basketUpliftPercentage,
        revenueInfluenced,
        incrementalRevenue,
        salesUpliftPercentage: 14.8, // Attributable uplift to total revenue
        conversionRate: 22.4,
        scanToPurchaseConversion: (aoeTransactions / engagement.totalScans) * 100,
        assistedSales: Math.floor(aoeTransactions * 0.65), // 65% of AOE sales had AI chat interaction
        offerRedemptionRate: 18.2,
        totalRedeemedValue: 7280.50,
        aoeTransactions
    };
    
    return {
        engagement,
        conversion,
        overallPerformance: `The Persistent Intelligence Layer is demonstrating high velocity adoption with an incremental revenue contribution of R${incrementalRevenue.toLocaleString()}. Identified Profile conversion is strong at 36.8%, and the scan-to-purchase conversion is outperforming industry benchmarks by 2.4x.`,
        conclusions: `- AI Guidance is directly responsible for a R${basketSizeIncreaseRand.toFixed(2)} increase in average basket size.\n- 65% of influenced sales are 'Assisted Sales', where the AI Assistant directly answered shopper questions.\n- Mobile OTP remains the dominant identity entry point, capturing high-intent shoppers instantly.`,
        recommendations: "- Scale 'Assisted Sales' by integrating real-time stock availability into AI responses.\n- Deploy RMN placements targeting the 'Incremental Revenue' items to further boost high-margin conversions.\n- Refine the scan-to-purchase journey for low-conversion categories identified in the Intent-Gap analysis."
    };
  }
);
