import {
  buildAriFinancialIntelligence,
  type AriFinancialNarrativeProvider,
} from '@/lib/ari-financial-intelligence';
import type { ProfitRoiInterpretation } from '@/lib/schemas/profit-roi-interpretation';

function interpretation(): ProfitRoiInterpretation {
  return {
    status: 'LIMITED_EVIDENCE',
    statusDetail: 'Authoritative attributed sales exist, but E4 counterfactual evidence is unavailable.',
    factualObservations: [
      {
        statementId: 'attributed_sales',
        text: 'R1,250 is deterministically attributed sales and is not incremental sales or revenue generated by iNteract.',
        supportingMetricIds: ['commerce_attributed_sales'],
        evidenceLevel: 'E2',
        evidenceRefs: ['deterministic_attribution'],
      },
    ],
    identifiedIndicators: [],
    suggestedActions: [
      {
        statementId: 'action_counterfactual_unavailable',
        text: 'Establish an approved counterfactual before calculating incremental sales or sales uplift.',
        supportingMetricIds: ['incremental_sales'],
        evidenceLevel: 'E4',
        evidenceRefs: ['counterfactual'],
      },
    ],
  };
}

describe('buildAriFinancialIntelligence', () => {
  test('remains operational without a generative provider', async () => {
    const result = await buildAriFinancialIntelligence(interpretation());

    expect(result.mode).toBe('DETERMINISTIC');
    expect(result.narrative.summary).toContain(
      'not incremental sales or revenue generated by iNteract'
    );
    expect(result.narrative.actions).toContain(
      'Establish an approved counterfactual before calculating incremental sales or sales uplift.'
    );
  });

  test('uses a valid provider narrative without replacing authoritative interpretation', async () => {
    const provider: AriFinancialNarrativeProvider = {
      enhance: async () => ({
        summary: 'Ari has identified authoritative attributed sales.',
        observations: ['Attributed sales are measured at E2.'],
        actions: ['Establish the required E4 counterfactual.'],
      }),
    };

    const source = interpretation();
    const result = await buildAriFinancialIntelligence(source, provider);

    expect(result.mode).toBe('ENHANCED');
    expect(result.interpretation).toEqual(source);
    expect(result.narrative.summary).toBe(
      'Ari has identified authoritative attributed sales.'
    );
  });

  test('survives provider failure and returns deterministic intelligence', async () => {
    const provider: AriFinancialNarrativeProvider = {
      enhance: async () => {
        throw new Error('provider unavailable');
      },
    };

    const result = await buildAriFinancialIntelligence(
      interpretation(),
      provider
    );

    expect(result.mode).toBe('DETERMINISTIC');
    expect(result.narrative.observations[0]).toContain(
      'not incremental sales'
    );
  });

  test('rejects malformed provider output and returns deterministic intelligence', async () => {
    const provider: AriFinancialNarrativeProvider = {
      enhance: async () => ({
        summary: '',
        observations: 'not-an-array',
        actions: [],
      }),
    };

    const result = await buildAriFinancialIntelligence(
      interpretation(),
      provider
    );

    expect(result.mode).toBe('DETERMINISTIC');
    expect(result.interpretation).toEqual(interpretation());
  });

  test('does not invent a numerical financial claim when authoritative interpretation has none', async () => {
    const empty: ProfitRoiInterpretation = {
      status: 'UNAVAILABLE',
      statusDetail: 'Authoritative financial evidence is not yet sufficient.',
      factualObservations: [],
      identifiedIndicators: [],
      suggestedActions: [
        {
          statementId: 'action_licence_cost_unavailable',
          text: 'Provide authoritative SaaS investment evidence before calculating licence cost offset or ROI.',
          supportingMetricIds: ['saas_investment'],
          evidenceLevel: 'E0',
          evidenceRefs: ['licence'],
        },
      ],
    };

    const result = await buildAriFinancialIntelligence(empty);

    expect(result.mode).toBe('DETERMINISTIC');
    expect(result.narrative.summary).not.toMatch(/R\d|[0-9]+%/);
    expect(result.narrative.summary).toContain('evidence-constrained');
  });
});
