'use client';

import { useState, useTransition, useEffect } from 'react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { 
  QrCode, User, Clock, TrendingUp, ShoppingCart, Percent, 
  Tag, Sparkles, AlertTriangle, UserCheck, ShieldCheck, 
  Fingerprint, Phone, Chrome, Smartphone, Mail, Download,
  Loader2, ArrowUp, DollarSign, Activity, BarChart3, Target
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import TopProductsTable from '@/components/dashboard/top-products-table';
import { Separator } from '@/components/ui/separator';
import TimeBasedPerformanceChart from '@/components/dashboard/time-based-performance-chart';
import { Button } from '@/components/ui/button';
import { analyzeEngagementMetrics, AnalyzeEngagementMetricsOutput } from '@/ai/flows';
import { Skeleton } from '@/components/ui/skeleton';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import SalesFunnelChart from '@/components/dashboard/sales-funnel-chart';
import { useToast } from '@/hooks/use-toast';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

export default function RoiPage() {
  const [metricsData, setMetricsData] = useState<AnalyzeEngagementMetricsOutput | null>(null);
  const [analysis, setAnalysis] = useState<AnalyzeEngagementMetricsOutput | null>(null);
  const [isAnalyzing, startAnalyzing] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  useEffect(() => {
    const fetchInitialData = async () => {
      try {
        const result = await analyzeEngagementMetrics({});
        setMetricsData(result);
      } catch (e) {
        console.error(e);
        setError("Could not load Intelligence ROI metrics. Please check connectivity.");
      }
    };
    fetchInitialData();
  }, []);

  const handleAnalyzeMetrics = () => {
    setError(null);
    startAnalyzing(async () => {
      if (metricsData) {
        setAnalysis(metricsData);
      } else {
        setError("Intelligence data stream is not available for analysis.");
      }
    });
  };

  const handleExport = (format: string) => {
    toast({
        title: `Generating Executive ROI Report (${format})...`,
        description: "Your detailed Decision Intelligence ROI analysis is being prepared.",
    });
  };
  
  const funnelData = metricsData ? {
    scans: metricsData.engagement.totalScans,
    interactions: metricsData.engagement.uniqueScans,
    conversions: Math.round(metricsData.engagement.uniqueScans * (metricsData.conversion.offerRedemptionRate / 100)),
    sales: metricsData.conversion.aoeTransactions,
  } : null;

  const topProductsData = [
    { id: '1', name: 'Eco-Friendly Water Bottle', scans: 1254, category: 'Lifestyle', trend: [30, 40, 35, 50, 45, 60] },
    { id: '2', name: 'Wireless Charging Pad', scans: 980, category: 'Electronics', trend: [20, 25, 22, 30, 28, 35] },
    { id: '3', name: 'Smart Notebook', scans: 872, category: 'Stationery', trend: [15, 18, 20, 25, 22, 30] },
    { id: '4', name: 'Canvas Tote Bag', scans: 765, category: 'Accessories', trend: [10, 15, 12, 18, 20, 25] },
    { id: '5', name: 'Aromatic Candle', scans: 654, category: 'Home Goods', trend: [5, 8, 7, 10, 12, 15] },
  ];
  
  const timeBasedPerformanceData = [
    { time: 'Mar', engagement: 4.5, conversion: 2.1 },
    { time: 'Apr', engagement: 4.8, conversion: 2.5 },
    { time: 'May', engagement: 5.1, conversion: 2.8 },
    { time: 'Jun', engagement: 5.3, conversion: 3.1 },
    { time: 'Jul', engagement: 5.8, conversion: 3.4 },
    { time: 'Aug', engagement: 6.2, conversion: 3.8 },
  ];

  return (
    <div className="space-y-8">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold tracking-tight mb-2">
            Economic Impact & Financial ROI
          </h2>
          <p className="text-muted-foreground max-w-3xl">
            Proving the net financial value generated by the Persistent Intelligence Layer.
          </p>
        </div>
        <div className="flex gap-3">
             <DropdownMenu>
                <DropdownMenuTrigger asChild>
                    <Button variant="outline" className="gap-2">
                        <Download className="h-4 w-4" /> Export Report
                    </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                    <DropdownMenuItem onClick={() => handleExport('PDF')}>Download Executive PDF</DropdownMenuItem>
                    <DropdownMenuItem onClick={() => handleExport('CSV')}>Raw Economic Data (CSV)</DropdownMenuItem>
                </DropdownMenuContent>
            </DropdownMenu>
            <Button onClick={handleAnalyzeMetrics} disabled={isAnalyzing || !metricsData} className="gap-2">
                <Sparkles className="h-4 w-4" />
                Analyze Economic Delta
            </Button>
        </div>
      </div>

      {isAnalyzing && (
        <Card className="border-accent bg-accent/5">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-accent"><Sparkles className="h-5 w-5"/> Intelligence ROI Audit Active</CardTitle>
            <CardDescription>Synthesizing economic metrics from the infrastructure stream...</CardDescription>
          </CardHeader>
          <CardContent className="py-6 flex justify-center"><Loader2 className="h-8 w-8 animate-spin text-accent" /></CardContent>
        </Card>
      )}

      {error && (
          <Alert variant="destructive">
              <AlertTriangle className="h-4 w-4" />
              <AlertTitle>Audit Friction</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
          </Alert>
      )}

      {analysis && (
        <Card className="bg-accent/10 border-accent shadow-md border-2">
            <CardHeader>
                 <CardTitle className="flex items-center gap-2 text-sm uppercase font-black tracking-widest"><Sparkles className="text-accent h-4 w-4"/> AI Economic Conclusion</CardTitle>
            </CardHeader>
            <CardContent className="grid md:grid-cols-2 gap-8">
                <div>
                    <h3 className="font-bold text-xs text-muted-foreground uppercase mb-2">ROI Performance</h3>
                    <p className="text-sm text-foreground whitespace-pre-wrap leading-relaxed">{analysis.overallPerformance}</p>
                </div>
                <Separator className="md:hidden" />
                 <div>
                    <h3 className="font-bold text-xs text-muted-foreground uppercase mb-2">Economic Action Plan</h3>
                    <p className="text-sm text-foreground whitespace-pre-wrap leading-relaxed">{analysis.recommendations}</p>
                </div>
            </CardContent>
        </Card>
      )}

      {/* CORE ECONOMIC PROOF SECTION */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card className="border-primary/20 bg-primary/5">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-[10px] font-black uppercase text-primary/60 tracking-widest">Revenue Influenced</CardTitle>
              <DollarSign className="h-4 w-4 text-primary" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-black">R{metricsData?.conversion.revenueInfluenced.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) || '---'}</div>
              <p className="text-[10px] text-muted-foreground mt-2">Total sales value from engaged shoppers.</p>
            </CardContent>
          </Card>

          <Card className="border-primary/20 bg-primary/5 shadow-inner">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-[10px] font-black uppercase text-primary/60 tracking-widest">Incremental Revenue</CardTitle>
              <ArrowUp className="h-4 w-4 text-green-600" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-black text-green-600">R{metricsData?.conversion.incrementalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) || '---'}</div>
              <p className="text-[10px] text-muted-foreground mt-2">Net new revenue created by Intelligence guidance.</p>
            </CardContent>
          </Card>

          <Card className="border-primary/20 bg-primary/5">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-[10px] font-black uppercase text-primary/60 tracking-widest">Sales Uplift</CardTitle>
              <Percent className="h-4 w-4 text-primary" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-black">+{metricsData?.conversion.salesUpliftPercentage.toFixed(1) || '---'}%</div>
              <p className="text-[10px] text-muted-foreground mt-2">Attributable growth in total store performance.</p>
            </CardContent>
          </Card>
      </div>

      <Separator />

      {/* DETAILED CONVERSION & BASKET SECTION */}
      <div className="grid gap-6 lg:grid-cols-2">
           <Card>
                <CardHeader>
                    <CardTitle className="text-lg">Basket Size Delta</CardTitle>
                    <CardDescription>Comparison between unguided and intelligence-guided shoppers.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-6 pt-2">
                    <div className="flex justify-between items-end">
                        <div className="space-y-1">
                            <p className="text-[10px] font-black uppercase text-muted-foreground tracking-widest">Intelligence Guided</p>
                            <p className="text-4xl font-black">R{metricsData?.conversion.avgBasketSizeAoe.toFixed(2) || '---'}</p>
                        </div>
                        <div className="text-right space-y-1">
                            <p className="text-[10px] font-black uppercase text-muted-foreground tracking-widest">Unguided Baseline</p>
                            <p className="text-2xl font-bold text-muted-foreground">R{metricsData?.conversion.avgBasketSizeNonAoe.toFixed(2) || '---'}</p>
                        </div>
                    </div>
                    <div className="p-4 bg-green-50 rounded-xl border border-green-100 flex items-center justify-between">
                        <div>
                            <p className="text-xs font-bold text-green-700">Basket Size Increase (Rand)</p>
                            <p className="text-xl font-black text-green-800">R{metricsData?.conversion.basketSizeIncreaseRand.toFixed(2) || '---'}</p>
                        </div>
                        <div className="text-right">
                             <p className="text-xs font-bold text-green-700">Basket Size Increase (%)</p>
                            <p className="text-xl font-black text-green-800">+{metricsData?.conversion.basketSizeIncreasePercent.toFixed(1) || '---'}%</p>
                        </div>
                    </div>
                </CardContent>
           </Card>

           <div className="grid gap-4 sm:grid-cols-2">
                <Card>
                    <CardHeader className="pb-2">
                        <CardTitle className="text-[10px] font-black uppercase text-muted-foreground tracking-widest flex items-center gap-2">
                            <BarChart3 className="h-3 w-3" /> Assisted Sales
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="text-3xl font-black">{metricsData?.conversion.assistedSales.toLocaleString() || '---'}</div>
                        <p className="text-[10px] text-muted-foreground mt-1">Sales directly guided by AI Assistant interaction.</p>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="pb-2">
                        <CardTitle className="text-[10px] font-black uppercase text-muted-foreground tracking-widest flex items-center gap-2">
                            <Target className="h-3 w-3" /> Scan-to-Purchase
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="text-3xl font-black">{metricsData?.conversion.scanToPurchaseConversion.toFixed(1) || '---'}%</div>
                        <p className="text-[10px] text-muted-foreground mt-1">Conversion efficiency from scan to transaction.</p>
                    </CardContent>
                </Card>
                <Card className="sm:col-span-2">
                    <CardHeader className="pb-2">
                        <CardTitle className="text-[10px] font-black uppercase text-muted-foreground tracking-widest">Global Conversion Rate</CardTitle>
                    </CardHeader>
                    <CardContent className="flex items-center justify-between">
                        <div className="text-4xl font-black">{metricsData?.conversion.conversionRate.toFixed(1) || '---'}%</div>
                        <Badge className="bg-primary text-white font-black text-[10px]">2.4x Benchmarks</Badge>
                    </CardContent>
                </Card>
           </div>
      </div>

      <Separator />

      {/* RETAINER METRICS: CORE ENGAGEMENT */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Total Scans</CardTitle>
            <QrCode className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{metricsData?.engagement.totalScans.toLocaleString() || '---'}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Unique Scans</CardTitle>
            <User className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{metricsData?.engagement.uniqueScans.toLocaleString() || '---'}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Engagement Rate</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{metricsData ? `${metricsData.engagement.scanRate.toFixed(2)}%` : '---'}</div>
          </CardContent>
        </Card>
         <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Dwell Time</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{metricsData ? `${metricsData.engagement.engagementDuration}s` : '---'}</div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-8 lg:grid-cols-2">
           {funnelData ? (
               <SalesFunnelChart data={funnelData} />
            ) : (
                <Card className="h-96 flex items-center justify-center bg-muted/50"><Loader2 className="animate-spin" /></Card>
            )}
            <TopProductsTable data={topProductsData} />
      </div>

      <Separator />

      <TimeBasedPerformanceChart 
        data={timeBasedPerformanceData} 
        title="Infrastructure Performance Trend"
        description="Month-over-month adoption and economic influence."
      />
    </div>
  );
}
