
'use client';

import { useState, useTransition, useEffect } from 'react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { 
  UserCheck, Clock, TrendingUp, ShoppingCart, Percent, 
  Sparkles, AlertTriangle, ArrowUp, DollarSign, Target, BarChart3,
  Download, Loader2, User, QrCode, ShieldCheck, ListChecks, History
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import TopProductsTable from '@/components/dashboard/top-products-table';
import { Separator } from '@/components/ui/separator';
import TimeBasedPerformanceChart from '@/components/dashboard/time-based-performance-chart';
import { Button } from '@/components/ui/button';
import { analyzeEngagementMetrics, attributeTransactions, type AnalyzeEngagementMetricsOutput, type AttributionReport } from '@/ai/flows';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import SalesFunnelChart from '@/components/dashboard/sales-funnel-chart';
import { useToast } from '@/hooks/use-toast';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

export default function RoiPage() {
  const [metricsData, setMetricsData] = useState<AnalyzeEngagementMetricsOutput | null>(null);
  const [attributionReport, setAttributionReport] = useState<AttributionReport | null>(null);
  const [analysis, setAnalysis] = useState<AnalyzeEngagementMetricsOutput | null>(null);
  const [isAnalyzing, startAnalyzing] = useTransition();
  const [isAttributing, startAttribution] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  useEffect(() => {
    const fetchInitialData = async () => {
      try {
        const result = await analyzeEngagementMetrics({});
        setMetricsData(result);
        
        startAttribution(async () => {
            const attr = await attributeTransactions('simulated-retailer-id');
            setAttributionReport(attr);
        });
      } catch (e) {
        setError("Could not load financial ROI metrics. Please check connectivity.");
      }
    };
    fetchInitialData();
  }, []);

  const handleAnalyzeMetrics = () => {
    setError(null);
    startAnalyzing(async () => {
      if (metricsData) {
        setAnalysis(metricsData);
      } else {
        setError("Intelligence stream is not available for analysis.");
      }
    });
  };

  const handleExport = (format: string) => {
    toast({
        title: `Generating Executive ROI Report (${format})...`,
        description: "Your session-based behavioural ROI analysis is being prepared.",
    });
  };
  
  const funnelData = metricsData ? {
    scans: metricsData.engagement.totalScans,
    interactions: metricsData.engagement.uniqueScans,
    conversions: Math.round(metricsData.engagement.uniqueScans * (metricsData.conversion.offerRedemptionRate / 100)),
    sales: metricsData.conversion.aoeTransactions,
  } : null;

  return (
    <div className="space-y-8">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-black tracking-tight mb-2">
            Economic Impact Architecture
          </h2>
          <p className="text-muted-foreground max-w-3xl">
            Proving the net financial value generated by session-based intelligence guidance.
          </p>
        </div>
        <div className="flex gap-3">
             <DropdownMenu>
                <DropdownMenuTrigger asChild>
                    <Button variant="outline" className="gap-2 font-bold text-[10px] uppercase tracking-widest">
                        <Download className="h-4 w-4" /> Export Economic Report
                    </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                    <DropdownMenuItem onClick={() => handleExport('PDF')}>Download Executive Summary</DropdownMenuItem>
                    <DropdownMenuItem onClick={() => handleExport('CSV')}>Raw Session Events (CSV)</DropdownMenuItem>
                </DropdownMenuContent>
            </DropdownMenu>
            <Button onClick={handleAnalyzeMetrics} disabled={isAnalyzing || !metricsData} className="gap-2 font-bold text-[10px] uppercase tracking-widest">
                <Sparkles className="h-4 w-4 text-accent" />
                Audit Intelligence Layer
            </Button>
        </div>
      </div>

      <Alert className="bg-primary/5 border-primary/20">
        <ShieldCheck className="h-4 w-4 text-primary" />
        <AlertTitle className="text-[10px] font-black uppercase tracking-widest">Attribution Integrity Guard</AlertTitle>
        <AlertDescription className="text-xs">
          All financial associations are currently based on <strong>verified session-level co-occurrence</strong>. No causal attribution is claimed.
        </AlertDescription>
      </Alert>

      {/* CORE ECONOMIC PROOF SECTION */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card className="border-primary/20 bg-primary shadow-sm text-primary-foreground">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-[10px] font-black uppercase opacity-70 tracking-widest">Revenue Influenced</CardTitle>
              <DollarSign className="h-4 w-4 opacity-70" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-black">
                {metricsData ? `R${metricsData.conversion.revenueInfluenced.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : <Skeleton className="h-8 w-24 bg-primary-foreground/20" />}
              </div>
              <p className="text-[10px] opacity-70 mt-2">Total sales value from session-anchored engagement.</p>
            </CardContent>
          </Card>

          <Card className="border-green-200 bg-green-50 shadow-sm border-2">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-[10px] font-black uppercase text-green-700 tracking-widest">Incremental Revenue</CardTitle>
              <ArrowUp className="h-4 w-4 text-green-600" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-black text-green-800">
                {metricsData ? `R${metricsData.conversion.incrementalRevenue.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : <Skeleton className="h-8 w-24 bg-green-200" />}
              </div>
              <p className="text-[10px] text-green-600 mt-2">Net financial uplift derived from Intelligence guidance.</p>
            </CardContent>
          </Card>

          <Card className="border-primary/10">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-[10px] font-black uppercase text-muted-foreground tracking-widest">Sales Uplift</CardTitle>
              <Percent className="h-4 w-4 text-primary" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-black text-primary">
                {metricsData ? `+${metricsData.conversion.salesUpliftPercentage.toFixed(1)}%` : <Skeleton className="h-8 w-20 bg-muted" />}
              </div>
              <p className="text-[10px] text-muted-foreground mt-2">Attributable growth in total platform performance.</p>
            </CardContent>
          </Card>
      </div>

      {/* Factual Transaction Audit Table */}
      <Card className="border-primary/10">
        <CardHeader className="bg-muted/30">
            <div className="flex justify-between items-center">
                <div>
                    <CardTitle className="text-lg font-black flex items-center gap-2">
                        <History className="h-5 w-5 text-primary" /> 
                        Transactional Journey Audit
                    </CardTitle>
                    <CardDescription>Factual co-occurrence log of verified transactions and Ari interactions.</CardDescription>
                </div>
                <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-200 text-[9px] font-black uppercase tracking-widest">
                    {attributionReport?.dataStatus || 'PENDING'} SOURCE
                </Badge>
            </div>
        </CardHeader>
        <CardContent className="pt-6">
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead className="text-[10px] font-black uppercase tracking-widest">Session ID</TableHead>
                        <TableHead className="text-[10px] font-black uppercase tracking-widest">POS Txn ID</TableHead>
                        <TableHead className="text-[10px] font-black uppercase tracking-widest">Ari Involvement</TableHead>
                        <TableHead className="text-[10px] font-black uppercase tracking-widest">Attribution Level</TableHead>
                        <TableHead className="text-right text-[10px] font-black uppercase tracking-widest">Timestamp</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {isAttributing ? (
                         <TableRow><TableCell colSpan={5} className="h-24 text-center"><Loader2 className="animate-spin mx-auto h-6 w-6 text-muted-foreground" /></TableCell></TableRow>
                    ) : attributionReport?.records.length === 0 ? (
                        <TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">No matching journeys discovered.</TableCell></TableRow>
                    ) : attributionReport?.records.map((record, i) => (
                        <TableRow key={i}>
                            <TableCell className="font-mono text-[10px] text-muted-foreground">{record.sessionId.substring(0, 12)}...</TableCell>
                            <TableCell className="font-mono text-[10px]">{record.transactionId?.substring(0, 12) || 'N/A'}...</TableCell>
                            <TableCell>
                                {record.ariInteraction ? (
                                    <Badge className="bg-primary/10 text-primary border-primary/20 text-[9px] font-bold uppercase">YES</Badge>
                                ) : <span className="text-[9px] font-bold text-muted-foreground uppercase opacity-50">NO</span>}
                            </TableCell>
                            <TableCell>
                                <span className="text-[10px] font-black uppercase tracking-tighter text-muted-foreground">
                                    {record.attributionLevel.replace(/_/g, ' ')}
                                </span>
                            </TableCell>
                            <TableCell className="text-right font-mono text-[10px] text-muted-foreground">
                                {record.transactionTimestamp ? new Date(record.transactionTimestamp).toLocaleTimeString() : '---'}
                            </TableCell>
                        </TableRow>
                    ))}
                </TableBody>
            </Table>
            <p className="text-[9px] italic text-muted-foreground mt-4 px-2">
                * This log joins transactions and Ari interactions strictly by Session ID. "Attribution Level" describes the observed journey depth, not causal force.
            </p>
        </CardContent>
      </Card>

      <Separator />

      <div className="grid gap-8 lg:grid-cols-2">
            {funnelData ? (
                <SalesFunnelChart data={funnelData} />
            ) : (
                <Card><CardContent className="flex justify-center py-10"><Loader2 className="h-10 w-10 animate-spin text-muted-foreground"/></CardContent></Card>
            )}
            <div className="space-y-6">
                <Card className="border-primary/10">
                    <CardHeader className="pb-2">
                        <CardTitle className="text-[10px] font-black uppercase text-muted-foreground tracking-widest flex items-center gap-2">
                            <BarChart3 className="h-3 w-3" /> Ari-Assisted Purchases
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="text-3xl font-black">{attributionReport?.ariAssistedPurchases || 0}</div>
                        <p className="text-[10px] text-muted-foreground mt-1">Confirmed POS transactions in Ari-active sessions.</p>
                    </CardContent>
                </Card>
                <TopProductsTable data={[]} />
            </div>
      </div>

      <Separator />

      <TimeBasedPerformanceChart 
        data={[]} 
        title="Infrastructure Performance Trend"
        description="Month-over-month adoption of GS1-aligned compatible architecture."
      />
    </div>
  );
}
