import { z } from 'zod';

import { OverviewEvidenceLevelSchema } from '@/lib/schemas/overview-intelligence';

/**
 * Authoritative Profit & ROI interpretation contract.
 *
 * GOVERNING INVARIANTS
 * - Interpretation is downstream of ProfitRoiSnapshot.
 * - Interpretation never creates or upgrades financial evidence.
 * - Missing evidence is described as an evidence state, never as zero.
 * - Attributed Sales is not Incremental Sales.
 * - Attributed Sales is not revenue generated by iNteract.
 * - Retail Media Revenue belongs to the retailer.
 * - Profit requires authoritative margin evidence.
 * - Sales uplift requires E4 counterfactual evidence.
 * - Generative AI is not an authority in this contract.
 */

export const ProfitRoiInterpretationStatusSchema = z.enum([
  'AVAILABLE',
  'NO_ACTIVITY',
  'LIMITED_EVIDENCE',
  'UNAVAILABLE',
]);

export type ProfitRoiInterpretationStatus = z.infer<
  typeof ProfitRoiInterpretationStatusSchema
>;

export const ProfitRoiInterpretationStatementSchema = z.object({
  statementId: z.string().min(1),
  text: z.string().min(1),
  supportingMetricIds: z.array(z.string().min(1)).min(1),
  evidenceLevel: OverviewEvidenceLevelSchema,
  evidenceRefs: z.array(z.string().min(1)),
});

export type ProfitRoiInterpretationStatement = z.infer<
  typeof ProfitRoiInterpretationStatementSchema
>;

export const ProfitRoiInterpretationSchema = z.object({
  status: ProfitRoiInterpretationStatusSchema,
  factualObservations: z.array(ProfitRoiInterpretationStatementSchema),
  identifiedIndicators: z.array(ProfitRoiInterpretationStatementSchema),
  suggestedActions: z.array(ProfitRoiInterpretationStatementSchema),
  statusDetail: z.string().min(1).optional(),
});

export type ProfitRoiInterpretation = z.infer<
  typeof ProfitRoiInterpretationSchema
>;
