import { ai } from '@/ai/genkit';
import type { AriFinancialNarrativeProvider } from '@/lib/ari-financial-intelligence';
import {
  AriFinancialNarrativeSchema,
  type AriFinancialNarrative,
} from '@/lib/schemas/ari-financial-intelligence';
import type { ProfitRoiInterpretation } from '@/lib/schemas/profit-roi-interpretation';

const ARI_FINANCIAL_MODEL = 'googleai/gemini-2.5-flash';
const ARI_FINANCIAL_PROVIDER_TIMEOUT_MS = 8000;

function buildPrompt(interpretation: ProfitRoiInterpretation): string {
  return `You are Ari, iNteract's retailer financial intelligence assistant.

You are receiving an AUTHORITATIVE DETERMINISTIC INTERPRETATION.
You are not receiving permission to calculate, infer, estimate, extrapolate,
reclassify, or manufacture financial evidence.

STRICT RULES:
1. Use only facts explicitly present in the supplied interpretation.
2. Do not create new numbers, percentages, Rand values, trends, comparisons,
   causation claims, uplift claims, incremental claims, profit claims, ROI
   claims, or attribution claims.
3. Do not promote evidence from E0/E1/E2/E3 to a higher evidence level.
4. Attributed sales are not incremental sales.
5. Attributed sales are not revenue generated by iNteract.
6. Retail Media revenue belongs to the retailer and is not iNteract revenue.
7. Incremental sales and sales uplift require authoritative E4 evidence.
8. Incremental commerce profit requires authoritative margin evidence.
9. ROI requires the complete authoritative reconciliation chain.
10. Preserve evidence limitations and recommended evidence actions.
11. Do not introduce outside knowledge.
12. Return JSON only, with exactly:
{
  "summary": "string",
  "observations": ["string"],
  "actions": ["string"]
}

AUTHORITATIVE INTERPRETATION:
${JSON.stringify(interpretation)}`;
}

export async function enhanceAriFinancialNarrative(
  interpretation: ProfitRoiInterpretation
): Promise<AriFinancialNarrative> {
  const generation = ai.generate({
    model: ARI_FINANCIAL_MODEL,
    prompt: buildPrompt(interpretation),
    output: {
      schema: AriFinancialNarrativeSchema,
    },
  });

  let timeout: ReturnType<typeof setTimeout> | undefined;

  try {
    const response = await Promise.race([
      generation,
      new Promise<never>((_, reject) => {
        timeout = setTimeout(
          () => reject(new Error('ARI_FINANCIAL_PROVIDER_TIMEOUT')),
          ARI_FINANCIAL_PROVIDER_TIMEOUT_MS
        );
      }),
    ]);

    if (!response.output) {
      throw new Error('ARI_FINANCIAL_PROVIDER_EMPTY_OUTPUT');
    }

    return AriFinancialNarrativeSchema.parse(response.output);
  } finally {
    if (timeout) {
      clearTimeout(timeout);
    }
  }
}

export const ariFinancialNarrativeProvider: AriFinancialNarrativeProvider = {
  enhance: enhanceAriFinancialNarrative,
};
