jest.mock('@/ai/genkit', () => ({
  ai: {
    generate: jest.fn(),
  },
}));

import { ai } from '@/ai/genkit';
import {
  ariFinancialNarrativeProvider,
  enhanceAriFinancialNarrative,
} from '@/ai/ari-financial-narrative-provider';
import type { ProfitRoiInterpretation } from '@/lib/schemas/profit-roi-interpretation';

const mockGenerate = ai.generate as jest.Mock;

function interpretation(): ProfitRoiInterpretation {
  return {
    status: 'LIMITED_EVIDENCE',
    statusDetail:
      'Attributed sales are available, but incremental evidence is unavailable.',
    factualObservations: [
      {
        statementId: 'attributed_sales',
        text: 'R1,250 is deterministically attributed sales and is not incremental sales or revenue generated by iNteract.',
        supportingMetricIds: ['commerce_attributed_sales'],
        evidenceLevel: 'E2',
        evidenceRefs: ['deterministic_attribution'],
      },
    ],
    identifiedIndicators: [],
    suggestedActions: [
      {
        statementId: 'action_counterfactual_unavailable',
        text: 'Establish an approved counterfactual before calculating incremental sales or sales uplift.',
        supportingMetricIds: ['incremental_sales'],
        evidenceLevel: 'E4',
        evidenceRefs: ['counterfactual'],
      },
    ],
  };
}

describe('Ari financial narrative provider', () => {
  beforeEach(() => {
    mockGenerate.mockReset();
  });

  test('supplies only deterministic interpretation to the model with strict authority constraints', async () => {
    mockGenerate.mockResolvedValue({
      output: {
        summary: 'Attributed sales are measured, while incrementality remains unavailable.',
        observations: ['Attributed sales are available at E2.'],
        actions: ['Establish the approved E4 counterfactual.'],
      },
    });

    await enhanceAriFinancialNarrative(interpretation());

    expect(mockGenerate).toHaveBeenCalledTimes(1);

    const request = mockGenerate.mock.calls[0][0];

    expect(request.model).toBe('googleai/gemini-2.5-flash');
    expect(request.prompt).toContain('AUTHORITATIVE DETERMINISTIC INTERPRETATION');
    expect(request.prompt).toContain(
      'Attributed sales are not incremental sales.'
    );
    expect(request.prompt).toContain(
      'Retail Media revenue belongs to the retailer'
    );
    expect(request.prompt).toContain(
      'Incremental sales and sales uplift require authoritative E4 evidence.'
    );
    expect(request.prompt).toContain(
      'R1,250 is deterministically attributed sales'
    );
  });

  test('returns schema-valid enhanced narrative', async () => {
    mockGenerate.mockResolvedValue({
      output: {
        summary: 'Authoritative attributed sales are available.',
        observations: ['E2 attributed sales are measured.'],
        actions: ['Establish E4 counterfactual evidence.'],
      },
    });

    const result =
      await ariFinancialNarrativeProvider.enhance(interpretation());

    expect(result).toEqual({
      summary: 'Authoritative attributed sales are available.',
      observations: ['E2 attributed sales are measured.'],
      actions: ['Establish E4 counterfactual evidence.'],
    });
  });

  test('fails closed when provider returns no structured output', async () => {
    mockGenerate.mockResolvedValue({
      output: null,
    });

    await expect(
      enhanceAriFinancialNarrative(interpretation())
    ).rejects.toThrow('ARI_FINANCIAL_PROVIDER_EMPTY_OUTPUT');
  });

  test('fails closed when provider output violates the narrative schema', async () => {
    mockGenerate.mockResolvedValue({
      output: {
        summary: '',
        observations: 'invalid',
        actions: [],
      },
    });

    await expect(
      enhanceAriFinancialNarrative(interpretation())
    ).rejects.toThrow();
  });
});
