import { validatePlatformAiGovernanceDefinitions } from './validate-governance-definitions';

const definitions = [
  {
    controlId: 'GOV-10-001',
    domain: 'GOV-10',
    title: 'Evidence-Grounded Recommendations',
    requirement:
      'Material product recommendations generated by governed AI must be supported by authoritative evidence relevant to the recommendation.',
    risk:
      'AI may recommend products using unsupported assumptions, incomplete product facts or generated claims that appear authoritative to shoppers.',
    controlStatement:
      'Ari must ground material recommendation claims in available authoritative product evidence and must constrain or qualify recommendations when the evidence is insufficient to support them.',
    authority: 'IMMUTABLE_PLATFORM_INVARIANT',
    applicability: 'CAPABILITY',
    enforcementTypes: [
      'EVIDENCE_BOUNDARY',
      'MODEL_INSTRUCTION',
      'APPLICATION_LOGIC',
    ],
    standardsMappings: [],
    visibility: 'READ_ONLY',
    retailerExtensibility: 'NONE',
  },
  {
    controlId: 'GOV-10-002',
    domain: 'GOV-10',
    title: 'Recommendation Criteria Integrity',
    requirement:
      'Criteria used to generate or explain recommendations must reflect the shopper request and authorized capability context rather than undisclosed substitution criteria.',
    risk:
      'Recommendations may appear responsive to shopper needs while actually being driven by unrelated commercial or system objectives.',
    controlStatement:
      'Ari must preserve material recommendation criteria derived from the shopper request and governed context and must not silently substitute conflicting commercial criteria as though they were shopper criteria.',
    authority: 'IMMUTABLE_PLATFORM_INVARIANT',
    applicability: 'CAPABILITY',
    enforcementTypes: [
      'APPLICATION_LOGIC',
      'MODEL_INSTRUCTION',
      'EVIDENCE_BOUNDARY',
    ],
    standardsMappings: [],
    visibility: 'READ_ONLY',
    retailerExtensibility: 'NONE',
  },
  {
    controlId: 'GOV-10-003',
    domain: 'GOV-10',
    title: 'Commercial Preference Independence',
    requirement:
      'Neutral AI recommendation claims must remain independent of undisclosed commercial preference, sponsorship or margin objectives.',
    risk:
      'Retailer or sponsor preference may be presented as independent AI judgment and improperly influence shopper decisions.',
    controlStatement:
      'Ari must not represent a recommendation as neutral or evidence-led when its material ranking or selection is determined by undisclosed sponsorship, margin, promotional or other commercial preference.',
    authority: 'IMMUTABLE_PLATFORM_INVARIANT',
    applicability: 'CAPABILITY',
    enforcementTypes: [
      'MODEL_INSTRUCTION',
      'APPLICATION_LOGIC',
      'AUTHORIZATION',
    ],
    standardsMappings: [],
    visibility: 'READ_ONLY',
    retailerExtensibility: 'NONE',
  },
  {
    controlId: 'GOV-10-004',
    domain: 'GOV-10',
    title: 'Comparison Integrity',
    requirement:
      'AI-generated product comparisons must use relevant, supportable and materially consistent comparison criteria.',
    risk:
      'Selective, unsupported or inconsistent comparison criteria may create a misleading impression that one product is superior to another.',
    controlStatement:
      'Ari must compare products using available authoritative evidence and relevant criteria, must not invent missing comparative facts and must identify material evidence limitations where they affect the comparison.',
    authority: 'IMMUTABLE_PLATFORM_INVARIANT',
    applicability: 'CAPABILITY',
    enforcementTypes: [
      'EVIDENCE_BOUNDARY',
      'MODEL_INSTRUCTION',
      'APPLICATION_LOGIC',
    ],
    standardsMappings: [],
    visibility: 'READ_ONLY',
    retailerExtensibility: 'NONE',
  },
  {
    controlId: 'GOV-10-005',
    domain: 'GOV-10',
    title: 'Cross-Sell Recommendation Integrity',
    requirement:
      'Cross-sell recommendations must have a supportable relationship to the shopper context and must remain subject to evidence, autonomy and commercial-influence controls.',
    risk:
      'AI may generate irrelevant or commercially optimized cross-sell suggestions that are presented as shopper-beneficial recommendations.',
    controlStatement:
      'Ari cross-sell recommendations must be grounded in a supportable relationship between the shopper context and recommended product and must not bypass evidence, autonomy, sponsorship or safety controls.',
    authority: 'IMMUTABLE_PLATFORM_INVARIANT',
    applicability: 'CAPABILITY',
    enforcementTypes: [
      'EVIDENCE_BOUNDARY',
      'MODEL_INSTRUCTION',
      'APPLICATION_LOGIC',
    ],
    standardsMappings: [],
    visibility: 'READ_ONLY',
    retailerExtensibility: 'NONE',
  },
  {
    controlId: 'GOV-10-006',
    domain: 'GOV-10',
    title: 'Recommendation Uncertainty & Alternatives',
    requirement:
      'Material uncertainty or insufficient evidence affecting a recommendation must be represented appropriately, and alternatives must not be suppressed solely to create false certainty.',
    risk:
      'AI may present one recommendation as definitive despite weak evidence or available alternatives, causing unjustified shopper reliance.',
    controlStatement:
      'Where evidence does not support a definitive recommendation, Ari must appropriately communicate uncertainty, constrain the recommendation or present relevant alternatives supported by the available evidence.',
    authority: 'IMMUTABLE_PLATFORM_INVARIANT',
    applicability: 'CAPABILITY',
    enforcementTypes: [
      'EVIDENCE_BOUNDARY',
      'MODEL_INSTRUCTION',
      'APPLICATION_LOGIC',
    ],
    standardsMappings: [],
    visibility: 'READ_ONLY',
    retailerExtensibility: 'NONE',
  },
  {
    controlId: 'GOV-10-007',
    domain: 'GOV-10',
    title: 'Recommendation Provenance & Explainability',
    requirement:
      'Material AI recommendations must retain sufficient provenance to support an appropriate explanation of the evidence and criteria underlying the recommendation.',
    risk:
      'Recommendations that cannot be traced to relevant evidence and criteria may be impossible to validate, investigate or explain.',
    controlStatement:
      'Governed recommendation processing must preserve sufficient evidence and criteria provenance to support proportionate explanation and audit without exposing protected internal reasoning or unnecessary sensitive data.',
    authority: 'IMMUTABLE_PLATFORM_INVARIANT',
    applicability: 'CAPABILITY',
    enforcementTypes: [
      'EVIDENCE_BOUNDARY',
      'AUDIT_LOGGING',
      'APPLICATION_LOGIC',
    ],
    standardsMappings: [],
    visibility: 'INTERNAL_ONLY',
    retailerExtensibility: 'NONE',
  },
] as const;

export const PLATFORM_AI_GOVERNANCE_V1_GOV_10 =
  validatePlatformAiGovernanceDefinitions(definitions);
